### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GeorgeS2019** [RhubarbVR/LibGodotSharp#1]
> Needs [godot repo](https://github.com/RhubarbVR/godot-lib) for generator
https://github.com/godotengine/godot-proposals/issues/6267
https://github.com/godotengine/godot/pull/72883

`
scons library_type=shared_library`

![image](https://user-images.githubusercontent.com/49812372/219647776-0987a10c-6915-4fae-b26c-4aac23b56c2f.png)

**Comment by GeorgeS2019** [comment]
![image](https://user-images.githubusercontent.com/49812372/219648817-3f10dfc9-7d89-4bc7-996b-c56e7700918b.png)

`extension_api.json`  will be generated

![image](https://user-images.githubusercontent.com/49812372/219648200-3502f563-f3f6-4175-951e-4912447efcfa.png)

**Comment by Faolan-Rad** [comment]
I am also planning on making a GitHub action that has all platforms built then add a nugget package. Sorry I forgot to add lib to the readme I just said it needed Godot repo in the readme

**Comment by GeorgeS2019** [comment]
There is a missing `ENUM `and I still could not get it work as it should.

**Comment by Faolan-Rad** [comment]
Would you be willing to Join the Godot discords vc in a minute

**Comment by GeorgeS2019** [comment]
Yes

**Comment by GeorgeS2019** [comment]
My Discord account => GeorgeFFM   Please send me link in case I miss the VC

**Comment by GeorgeS2019** [comment]
using this repos: https://github.com/RhubarbVR/godot-lib 

`scons library_type=shared_library target=template_release`

copy from the bin => godot.windows.template_release.x86_64.dll
Paste it in the LibGodotSharp\TestConsoleApp\bin\Debug\net7.0 =>   and rename to libgodot.dll

![WindowsTerminal_1rCOlDlk6N](https://user-images.githubusercontent.com/49812372/219977067-e0c226b2-2d12-470f-8a95-a5c66fca4215.gif)
