### ISSUE TITLE
Segfault on linux

### ISSUE THREAD

**Issue by duck-117** [RhubarbVR/LibGodotSharp#13]
Template project segfaults with exit code 139 on arch linux.

**Comment by Faolan-Rad** [comment]
It is due to how the memory allocations are happening in the generated code i do plan on moving it to use the standard c# generator in Godot itself which should help to elevate this problem and other problems but I have been working on my other projects at the moment

**Comment by Faolan-Rad** [comment]
Basically over time the memory starts drifting and i don't know where it is coming from so i have decided to try and make it use the work that has already been put into c# godot
